### ISSUE TITLE
Config options seems to be missing when parsed in schema.py

### ISSUE THREAD

**Issue by jiamings** [jrmcornish/cif#1]
Hi, thanks for implementing many different flow methods into a comprehensive repo! 
When I try to run the following command
```
./main.py --model resflow --dataset 2uniforms
```
I got the following error
```
File "cif/config/schemas.py", line 720, in add_lipschitz_config_to_resblocks
    layer["reduce_memory"] = config["reduce_memory"]
KeyError: 'reduce_memory'
```
Similar issues occur when I was trying the RealNVP model. I think there are some configs that are not loaded by default, which caused this issue?

**Comment by anthonycaterini** [comment]
Hi @jiamings and thank you for raising this issue. You are correct that we are missing some keys in the config -- you can add these yourself in the meantime by putting in 

`"act_norm": False`

in Line 31 and 

`"reduce_memory" : False`

in Line 62, both within `config/two_d.py`. This will be updated soon in the repo,

**Comment by jrmcornish** [comment]
Hi @jiamings - this should now be fixed on `master`. Please do reach out if the problem persists :slightly_smiling_face:

**Comment by jiamings** [comment]
Thanks! It work now.
